### ISSUE TITLE
在部署时遇到报错

### ISSUE THREAD

**Issue by WenHe233** [Lycreal/MiraiBot#10]
运行python3 run.py mirai://localhost:8080/ws?authKey=$authKey&qq=$qq后，
报错Traceback (most recent call last):
  File "run.py", line 7, in <module>
    app = Mirai(sys.argv[1])
  File "C:\Users\****************\AppData\Local\Programs\Python\Python37\lib\site-packages\mirai\application.py", line 94, in __init__
    raise ValueError("invaild url: wrong format")
ValueError: invaild url: wrong format
'qq' is not recognized as an internal or external command,
operable program or batch file.

**Comment by Lycreal** [comment]
$authKey和$qq是示意，换成你的真实authKey和qq，authKey和[mirai-api-http](https://github.com/project-mirai/mirai-api-http)中的配置保持一致

**Comment by Lycreal** [comment]
在windows系统将后面的 `mirai://localhost:8080/ws?authKey=$authKey&qq=$qq`  加上引号
