### ISSUE TITLE
你好我想问一些问题

### ISSUE THREAD

**Issue by TenXLiar** [Lycreal/MiraiBot#13]
我mirai 和mirai-api-http均已经部署好了，我自己单发消息也能发出去，你这边的功能，按照步骤终端运行后，并没有生效，终端上也没有任何反馈，测试Help也没有用，是不是哪里漏配置了

**Comment by Lycreal** [comment]
启动的命令行参数要和 mirai-api-http 的 setting.yml 内容对应，包括端口号， authkey，是否启用ws等。

能描述得更具体一些吗，比如你的启动参数，console启动方式，console和本程序的终端输出等等。

**Comment by TenXLiar** [comment]
你好，我没有表达清楚。我的操作步骤如下：(可能存在问题的点)用的MIraiOK,1.打开MiraiOK(这个是已经配置好的)，登陆机器人账号。2.运行run.py。观察没有发现任何反馈，终端也没有，如图所示
![image](https://user-images.githubusercontent.com/22612074/100178192-624a0d80-2f0e-11eb-8ae8-fff876344262.png)
![image](https://user-images.githubusercontent.com/22612074/100178212-6d9d3900-2f0e-11eb-85bb-cad8edc21ad3.png)

**Comment by Lycreal** [comment]
你需要在 mirai-api-http 中启用 websocket ，也就是图中的第 7 行

**Comment by Lycreal** [comment]
我之前没有用过powershell，我自己试了一下，`python3` 这个命令打开了微软商店，我不知道你所说的“发现任何反馈”是否是这个原因。建议你检查 python 是否安装成功并且能正常运行。

最简单的解决方案是将 `python3` 命令用 python 安装位置的绝对路径代替。

**Comment by TenXLiar** [comment]
你好，问题已经解决了，谢谢大佬。不过需要提醒一下，这个是基于python 3.8之后的版本，我的是3.7，在直播监控的代码中 :=功能暂不适用，可以在readme里提一下~
